version: '2'
volumes:
  db:
  staging:
  static:
  store:
services:
  django:
    image: uwaedu/mytardis_django:develop
    build: .
    ports:
      - '8001:8000'
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ADMINS=[('Dean Taylor','dean.taylor@uwa.edu.au'),]
      - DJANGO_ALLOWED_HOSTS=['localhost',]
      - DJANGO_EMAIL_SUBJECT_PREFIX="[TruDat.UWA]:"
      - DJANGO_DATETIME_FORMAT='jS F Y H:i'
      - DJANGO_DATE_FORMAT='jS F Y'
      - DJANGO_DEFAULT_FROM_EMAIL='donotreply-trudat@uwa.edu.au'
      - DJANGO_SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO', 'https')
      - GUNICORN_WORKER_CLASS=gevent
      - MYTARDIS_BIOFORMATS_ENABLE=True
      - MYTARDIS_SITE_TITLE=TruDat@UWA_Dev
      - MYTARDIS_RAPID_CONNECT_ENABLED=False
    env_file:
      - env.POSTGRES
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - static:/usr/src/app/static
      - store:/usr/src/app/var/store
  celery:
    image: uwaedu/mytardis_django:develop
    command: --loglevel=INFO --autoreload
    environment:
      - CELERY_ENABLE=True
      - MYTARDIS_BIOFORMATS_ENABLE=True
    env_file:
      - env.POSTGRES
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - store:/usr/src/app/var/store
  other:
    image: uwaedu/mytardis_django:develop
    command: ["tail","-f","/dev/null",]
    environment:
      - GUNICORN_ENABLE=False
    volumes:
      - staging:/usr/src/app/var/staging
      - static:/usr/src/app/static
      - store:/usr/src/app/var/store
      - ./src/mytardis/test.py:/usr/src/app/test.py
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums --locale=en_US.utf8
    env_file:
      - env.POSTGRES
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3
  haproxy:
    image: haproxy:1.7
    command: echo "haproxy disabled"
    links:
      - django
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:8443:8443'
    restart: 'no'
    volumes:
      - ./pki/localhost_chain.pem:/localhost_chain.pem
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
