version: '2'
volumes:
  db:
services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=['localhost','sci-nix-029']
      - DJANGO_EMAIL_SUBJECT_PREFIX="[MyTardisUWA] "
      - GUNICORN_WORKER_CLASS=gevent
      - MYTARDIS_SITE_TITLE=MyTardisUWA
    env_file:
      - env.DJANGO_EMAIL
    links:
      - db
  db:
    image: postgres
    environment:
      - DB_NAME=mytardis-dev
    volumes:
      - db:/var/lib/postgresql
