version: '2'
volumes:
  db:
  staging:
  static:
  store:
services:
  django:
    build: .
    ports:
      - '127.0.0.1:8005:8000'
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ADMINS=[('Dean Taylor','dean.taylor@uwa.edu.au'),]
      - DJANGO_ALLOWED_HOSTS=['localhost','sci-nix-029']
      - DJANGO_EMAIL_SUBJECT_PREFIX="[MyTardisUWA]:"
      - DJANGO_DATETIME_FORMAT='jS F Y H:i'
      - DJANGO_DATE_FORMAT='jS F Y'
      - DJANGO_DEFAULT_FROM_EMAIL='mytardis-cmca@uwa.edu.au'
      - GUNICORN_WORKER_CLASS=gevent
      - MYTARDIS_BIOFORMATS_FILTER_ENABLE=True
      - MYTARDIS_SITE_TITLE=MyTardisUWADev
      - MYTARDIS_RAPID_CONNECT_ENABLED=False
    env_file:
      - env.MYTARDIS_LDAP
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - static:/usr/src/app/static
      - store:/usr/src/app/var/store
  celery:
    image: mytardis_django
    command: --loglevel=INFO
    environment:
      - CELERY_ENABLE=True
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - store:/usr/src/app/var/store
  other:
    image: dockerdjango_django
    command: ["tail","-f","/dev/null",]
    environment:
      - GUNICORN_ENABLE=False
  db:
    image: postgres:9.5
    environment:
      - DB_NAME=mytardis-dev
    volumes:
      - db:/var/lib/postgresql
  rabbitmq:
    image: rabbitmq:3
