version: '2'
services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,sci-nix-029
      - DJANGO_EMAIL_SUBJECT_PREFIX="[MyTardisUWA] "
      - MYTARDIS_SITE_TITLE=MyTardisUWA
    env_file:
      - env.DJANGO_EMAIL

