version: '2'
volumes:
  db:
  staging:
  static:
  store:
services:
  django:
    build: .
    ports:
      - '127.0.0.1:8001:8000'
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ADMINS=[('Dean Taylor','dean.taylor@uwa.edu.au'),]
      - DJANGO_ALLOWED_HOSTS=['localhost',]
      - DJANGO_EMAIL_SUBJECT_PREFIX="[TruDat.UWA]:"
      - DJANGO_DATETIME_FORMAT='jS F Y H:i'
      - DJANGO_DATE_FORMAT='jS F Y'
      - DJANGO_DEFAULT_FROM_EMAIL='donotreply-trudat@uwa.edu.au'
      - GUNICORN_WORKER_CLASS=gevent
      - MYTARDIS_BIOFORMATS_ENABLE=True
      - MYTARDIS_SITE_TITLE=TruDat@UWA_Dev
      - MYTARDIS_RAPID_CONNECT_ENABLED=False
    env_file:
      - env.MYTARDIS_LDAP
      - env.POSTGRES
      - env.RAPID_CONNECT_CONFIG
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - static:/usr/src/app/static
      - store:/usr/src/app/var/store
      - ./src/authentication.py:/usr/src/app/tardis/tardis_portal/views/authentication.py
      - ./src/forms.py:/usr/src/app/tardis/tardis_portal/forms.py
      - ./src/widgets.py:/usr/src/app/tardis/tardis_portal/widgets.py
  celery:
    image: mytardis_django
    command: --loglevel=INFO --autoreload
    environment:
      - CELERY_ENABLE=True
      - MYTARDIS_BIOFORMATS_ENABLE=True
    env_file:
      - env.POSTGRES
    links:
      - db
      - rabbitmq
    volumes:
      - staging:/usr/src/app/var/staging
      - store:/usr/src/app/var/store
  other:
    image: mytardis_django
    command: ["tail","-f","/dev/null",]
    environment:
      - GUNICORN_ENABLE=False
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums --locale=en_US.utf8
    env_file:
      - env.POSTGRES
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3
